provider: dnsimple
major-version: 4
upstreamProviderOrg: dnsimple
env:
  DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
  DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}
makeTemplate: bridged
team: ecosystem
