provider: dnsimple
major-version: 4
env:
  DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
  DNSIMPLE_ACCOUNT: ${{ secrets.DNSIMPLE_ACCOUNT }}
makeTemplate: bridged
team: ecosystem
license:
  ignore:
    - github.com/oracle/terraform-provider-dnsimple/shim
